HRMS.Web/Controllers/PastEmploymentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HRMS.Entities;
using HRMS.DataAccess;
using System.IO;
using HRMS.Web.FileUpload;
using System.Configuration;
using HRMS.Entities.ViewModel;

namespace HRMS.Web.Controllers
{
    public class PastEmploymentController : BaseController
    {
        //
        // GET: /PastEmployment/
        public ActionResult Index(int Id = 0)
        {
            ViewBag.EmployeeID = Id;
            return View();

        }

        int LoginUser = 1;
        public ActionResult GetPastEmploymentList(int EmployeeID = 0)
        {

            //-------------------Grid Paging Info----------------------------------
            int pageMode = Convert.ToInt16(HttpContext.Items["PageMode"]);
           
            List<PastEmploymentModel> objPastEmploymentList = new List<PastEmploymentModel>();
            PastEmploymentDB objPastEmploymentDB = new PastEmploymentDB();
            objPastEmploymentList = objPastEmploymentDB.GetPastEmploymentList(EmployeeID);
            //---------------------------------------------
            var vList = new object();
            vList = new
            {
                aaData = (from item in objPastEmploymentList
                          select new
                          {
                               Actions = "<a class='btn btn-success btn-rounded btn-condensed btn-sm' onclick='AddPastEmployment(" + item.PastEmploymentID.ToString() + ',' + item.EmployeeID.ToString() + ")' title='Edit' ><i class='fa fa-pencil'></i></a> <a class='btn btn-danger btn-rounded btn-condensed btn-sm' onclick='DeleteChannelPastEmployment(" + item.PastEmploymentID.ToString() + ',' + item.EmployeeID.ToString() + ")' title='Delete' ><i class='fa fa-times'></i> </a>",
                              PastEmploymentID = item.PastEmploymentID,
                              FirstName = item.FirstName_1,
                              LastName = item.SurName_1,
                              CompanyName = item.CompanyName,
                              StartDate = (item.StartDate),
                              EndDate = (item.EndDate),
                              Department = item.Department,
                              Position = item.Position,
                              Role = item.Role,
                              refrence = item.EmpReferences,
                          }).ToArray() 
            };           
            return Json(vList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Edit(int Id = 0, int EmployeeID = 0)
        {
            ViewBag.EmployeeID = EmployeeID;
            PastEmploymentDB objPastEmploymentDB = new PastEmploymentDB();
            PastEmploymentModel objPastEmploymentModel = new PastEmploymentModel();
            if (Id != 0)
            {

                objPastEmploymentModel = objPastEmploymentDB.GetPastEmploymentByID(Id);
                objPastEmploymentModel.StartDate = objPastEmploymentModel.StartDate == "" ? "" : (objPastEmploymentModel.StartDate);
                objPastEmploymentModel.EndDate = objPastEmploymentModel.EndDate == "" ? "" : (objPastEmploymentModel.EndDate);

            }
            else
            {
                objPastEmploymentModel.EmployeeID = EmployeeID;
            }

            return View("Edit", objPastEmploymentModel);
        }


        public ActionResult UpdatePastEmplymentDetails(PastEmploymentModel PastEmploymentModel)
        {
            OperationDetails operationDetails = new OperationDetails();
            string result = "";
            string resultMessage = "";
            int PastEmploymentId = 0;
            PastEmploymentModel.Department = (PastEmploymentModel.Department == null ? "" : PastEmploymentModel.Department);
            PastEmploymentModel.Role = (PastEmploymentModel.Role == null ? "" : PastEmploymentModel.Role);
            PastEmploymentModel.EmpReferences = (PastEmploymentModel.EmpReferences == null ? "" : PastEmploymentModel.EmpReferences);
            PastEmploymentModel.Position = (PastEmploymentModel.Position == null ? "" : PastEmploymentModel.Position);
            if (Convert.ToDateTime(DataAccess.GeneralDB.CommonDB.SetCulturedDate(PastEmploymentModel.StartDate)) > Convert.ToDateTime(DataAccess.GeneralDB.CommonDB.SetCulturedDate(PastEmploymentModel.EndDate)))
            {
                result = "error";
                resultMessage = "Start date must be before end date";
                return Json(new { PastEmploymentId = PastEmploymentId, result = result, resultMessage = resultMessage }, JsonRequestBehavior.AllowGet);
            }


            UserContextViewModel objUserContextViewModel = new UserContextViewModel();
            objUserContextViewModel = (UserContextViewModel)Session["userContext"];
            PastEmploymentDB objPastEmploymentDB = new PastEmploymentDB();

            if (PastEmploymentModel.PastEmploymentID == 0)
            {
                PastEmploymentModel.CreatedBy = objUserContextViewModel.UserId;
                operationDetails = objPastEmploymentDB.AddPastEmployment(PastEmploymentModel);
                result = operationDetails.Message;
                PastEmploymentId = operationDetails.InsertedRowId;
            }
            else
            {
                PastEmploymentId = PastEmploymentModel.PastEmploymentID;
                PastEmploymentModel.ModifiedBy = objUserContextViewModel.UserId;
                operationDetails = objPastEmploymentDB.UpdatePastEmployment(PastEmploymentModel);
                result = operationDetails.Message;
            }

            if (result == "Success")
            {
                if (PastEmploymentModel.PastEmploymentID == 0)
                {
                    result = "success";
                    resultMessage = "Past employment details save successfully";
                }
                else if (PastEmploymentModel.PastEmploymentID != 0)
                {
                    result = "success";
                    resultMessage = "Past employment details save successfully";
                }
            }
            else
            {
                result = "error";
                resultMessage = "Technical error has occurred";
            }

            return Json(new { PastEmploymentID = PastEmploymentId, result = result, resultMessage = resultMessage }, JsonRequestBehavior.AllowGet);

        }


        public ActionResult Delete(int Id)
        {
            OperationDetails operationDetails = new OperationDetails();
            string result = "";
            string resultMessage = "";
            PastEmploymentDB objPastEmploymentDB = new PastEmploymentDB();
            operationDetails = objPastEmploymentDB.DeletePastEmployment(Id);

            if (operationDetails.Message == "Success")
            {
                result = "success";
                resultMessage = "Record deleted successfully";
            }
            else
            {
                result = "error";
                resultMessage = "Technical error has occurred";
            }
            return Json(new { PastEmploymentID = Id, result = result, resultMessage = resultMessage }, JsonRequestBehavior.AllowGet);
        }


        public ActionResult GetPastEmploymentDocsList(int Id = 0)
        {

            //-------------Data Objects--------------------
            PastEmploymentModel objPastEmployment = new PastEmploymentModel();

            PastEmploymentDB objPastEmploymentDB = new PastEmploymentDB();
            objPastEmployment.objPastEmploymentList = objPastEmploymentDB.GetPastEmploymentDocs(Id);
            objPastEmployment.PastEmploymentID = Id;
            //---------------------------------------------

            //var vList = new object();

            //vList = new
            //{
            //    aaData = (from item in objPastEmploymentList
            //              select new
            //              {

            //                  PastEmploymentID = item.PastEmploymentID,
            //                  FileName = "<a href='" + item.FilePath + "' target='_blank'  title='" + item.FileName + "' ><i class='fa fa-pencil'></i> " + item.FileName + "</a>",
            //                  Description = item.Description,
            //                  Size = item.FileSize,
            //                  Type = item.FileType,                                                          
            //                  Actions = "<a class='btn btn-primary' onclick='DeleteChannel(" + item.AttatchmentId.ToString() + ")' title='Delete' ><i class='fa fa-pencil'></i> Delete</a>",
            //              }).ToArray(),               
            //};


            return PartialView("PastEmploymentDocs", objPastEmployment);
        }




        [HttpPost]
        public ActionResult Upload(HttpPostedFileBase file, int PastEmploymentID, string Description, string FileType)
        {
            OperationDetails operationDetails = new OperationDetails();
            UserContextViewModel objUserContextViewModel = new UserContextViewModel();
            objUserContextViewModel = (UserContextViewModel)Session["userContext"];
            PastEmploymentDB objPastEmploymentDB = new PastEmploymentDB();
            PastEmploymentModel objPastEmploymentModel = new PastEmploymentModel();
            try
            {

                //for (int i = 0; i < Request.Files.Count; i++)
                //{

                //}
                string Fullpath = "";
                string filename = "";
                string type = "";
                if (file != null && file.ContentLength > 0)
                {
                    var Directory = Server.MapPath(ConfigurationManager.AppSettings["PastEmploymentDocsPath"].ToString());
                    //file.SaveAs(path);
                    FileUploadHelper.UploadFile(Directory, file, PastEmploymentID, out Fullpath, out filename);

HRMS.Web/Views/PastEmployment/Edit.cshtml
@model HRMS.Entities.PastEmploymentModel
@{
    ViewBag.Title = "Edit";
    Layout = null;
}

@*<div class="row" style="margin:5px">
        <div class="col-sm-12 margin_bottom">

            <input type="button" value="Add" id="btn_add" class="btn btn-primary" />

            <input type="button" value="Back To Profile" id="btn_BackProfile" class="btn btn-primary" />
        </div>
    </div>*@

@*@Html.Hidden("EmployeeID", (int)ViewBag.EmployeeID, new { @ID = "Empid" })*@

@*<style type="text/css">
    h2 {
        padding: 10px 0 0 10px !important;
    }
</style>*@

<div class="panel panel-default">
    @using (Ajax.BeginForm("UpdatePastEmplymentDetails", "PastEmployment", new AjaxOptions { OnFailure = "onFailure", OnSuccess = "onSuccessPastEmployment" }, new { id = "frmAddEmploymentPast" }))
    {
        @Html.HiddenFor(m => m.PastEmploymentID)
        @Html.HiddenFor(m => m.EmployeeID)
        <div class="panel-body @*form-group-separated*@">
            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">                    
                </div>
                <div class="col-sm-8">
                    <div class="text-right">
                        <span class="required-field">*</span>&nbsp;Indicate required fields
                    </div>                    
                </div>
            </div>
            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">
                    <label class="label-form"><span class="required-field">*</span>&nbsp;Company Name:</label>
                </div>
                <div class="col-sm-8">                    
                    @Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control", @required = "required" })
                    @Html.ValidationMessageFor(m => m.CompanyName)
                </div>
            </div>
            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">
                    <label class="label-form"><span class="required-field">*</span>&nbsp;Start Date:</label>
                </div>
                <div class="col-sm-8">
                    <div class="input-group">
                        <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                        @Html.TextBoxFor(m => m.StartDate, new { @class = "DOB datepicker form-control" })
                        @Html.ValidationMessageFor(m => m.StartDate)
                    </div>
                </div>
            </div>
            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">
                    <label class="label-form"><span class="required-field">*</span>&nbsp;End Date:</label>
                </div>
                <div class="col-sm-8">
                    <div class="input-group">
                        <span class="input-group-addon add-on"><span class="fa fa-calendar"></span></span>
                        @Html.TextBoxFor(m => m.EndDate, new { @class = "DOB datepicker form-control" })
                        @Html.ValidationMessageFor(m => m.EndDate)
                    </div>
                </div>
            </div>
            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">
                    <label class="label-form">Department:</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Department, new { @class = "form-control" })
                </div>
            </div>

            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">
                    <label class="label-form">Position:</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Position, new { @class = "form-control" })
                </div>
            </div>

            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">
                    <label class="label-form">Role:</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextBoxFor(m => m.Role, new { @class = "form-control" })
                </div>
            </div>
            <div class="col-sm-12 margin_bottom">
                <div class="col-sm-4 padding-0">
                    <label class="label-form">References:</label>
                </div>
                <div class="col-sm-8">
                    @Html.TextAreaFor(m => m.EmpReferences, new { @class = "form-control" })
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="button" value="Cancel" class="btn btn-primary pull-left" onclick="CloseClosetModel('#frmAddEmploymentPast');" />
            <input type="submit" value="Save" class="btn btn-primary pull-right" @*onclick="ValidateForm();"*@ />
        </div>
    }

</div>
<script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
<script src="~/Scripts/Custom/LaunchDatepicker.js"></script>
<script type="text/javascript">


    $(document).ready(function () {
        $('#collapseOne').toggleClass('collapse', 'in');
    });

    function onSuccessPastEmployment(data) {
        if (data.result == "success") {
            ShowMessage("success", data.resultMessage);
            location.reload();
            //CloseClosetModel('#frmAddEmploymentPast');
            //getPastEmploymentGrid($('#EmployeeID').val());
        } else {
            ShowMessage("error", data.resultMessage);
        }
    }

</script>

HRMS.Web/Views/PastEmployment/Index.cshtml
@{
    ViewBag.Title = "HRMS - Employee > Past Employment";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Breadcrumb
{
    <ul class="breadcrumb">
        <li><a href="/Home/Index"><i class="fa fa-home"></i>Home</a></li>
        <li><a href="/Employee/ListEmployee">Employee List</a></li>
        <li><a href="/ViewEmployeeProfile/Index/@ViewBag.EmployeeID">Employee Profile</a></li>
        <li class="active">Past Employment</li>
    </ul>
}

@*<style type="text/css">
    .headerbtn {
        padding: 10px 0;
    }

    #tbl_PastEmployment {
        width: 100%;
    }

        #tbl_PastEmployment td:first-child {
            width: 80px;
        }
</style>*@


@Html.Hidden("EmployeeID", (int)ViewBag.EmployeeID, new { @ID = "Empid" })

<div class="row">
    <div class="col-md-12 margin_bottom">
        <input type="button" value="Add" id="btn_add" class="btn btn-primary" />
        <input type="button" value="Back To Profile" id="btn_BackProfile" class="btn btn-primary" />
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-star-empty"></span> Past Employment</h3>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table id="tbl_PastEmployment" class="display table table-bordered table-striped"></table>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts
{

    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/Custom/PastEmployment.js"></script>

}

HRMS.Web/Views/PastEmployment/PastEmploymentDetails.cshtml
@model HRMS.Entities.PastEmploymentModel

<script>
    function SucessPastEmploymentDetails(arg) {
        $.unblockUI();
        $('#PastEmploymentID').val(arg.PastEmploymentID);
        ShowMessage(arg.result, arg.resultMessage);
        window.location.href = "/PastEmployment/Index/" + $('#EmployeeID').val();
    }

    function BeginPastEmploymentDetails() {
        //$.unblockUI();
        $.blockUI();
    }
</script>


@using (Ajax.BeginForm("UpdatePastEmplymentDetails", "PastEmployment", new AjaxOptions { OnSuccess = "SucessPastEmploymentDetails", OnBegin = "BeginPastEmploymentDetails" }))
{
    @*@Html.HiddenFor(m => m.LocationID, new { @class="LocidforLocationDetails" })*@
    @Html.HiddenFor(m => m.PastEmploymentID, new { @class = "hiddenEmploymentID" })
    @Html.HiddenFor(m => m.EmployeeID, new { @class = "hiddenEmployeeID" })

    <div class="form-group row">
        <div class="col-md-12">
            <div class="col-md-12">
                <div class="col-md-2">@Html.LabelFor(m => m.CompanyName, new { @class = "" })</div>
                <div class="col-md-10">@Html.TextBoxFor(m => m.CompanyName, new { @class = "form-control" }) 
                 @Html.ValidationMessageFor(m => m.CompanyName)</div>
            </div>

            <div class="col-md-12">
                <div class="col-md-2">@Html.LabelFor(m => m.StartDate)</div>
                <div class="col-md-10">@Html.TextBoxFor(m => m.StartDate, new { @class = "datepicker form-control" })
                @Html.ValidationMessageFor(m => m.StartDate)</div>
            </div>

            <div class="col-md-12">
                <div class="col-md-2">@Html.LabelFor(m => m.EndDate)</div>
                <div class="col-md-10">@Html.TextBoxFor(m => m.EndDate, new { @class = "datepicker form-control" })</div> @*,@value = @Model.StartDate.Value.ToShortDateString()*@
                @Html.ValidationMessageFor(m => m.EndDate)
            </div>
            <div class="col-md-12">
                <div class="col-md-2">@Html.LabelFor(m => m.Department)</div>
                <div class="col-md-10">@Html.TextBoxFor(m => m.Department, new { @class = "form-control" })</div><td>@Html.ValidationMessageFor(m => m.Department)</td>
            </div>
            <div class="col-md-12">
                <div class="col-md-2">
                    @Html.LabelFor(m => m.Position)
                </div>
                <div class="col-md-10">@Html.TextBoxFor(m => m.Position, new { @class = "form-control" })</div><td>@Html.ValidationMessageFor(m => m.Position)</td>
            </div>
            <div class="col-md-12">
                <div class="col-md-2">@Html.LabelFor(m => m.Role)</div>
                <div class="col-md-10">@Html.TextBoxFor(m => m.Role, new { @class = "form-control" })</div><td>@Html.ValidationMessageFor(m => m.Role)</td>
            </div>
            <div class="col-md-12">
                <div class="col-md-2">@Html.LabelFor(m => m.EmpReferences)</div><div class="col-md-5">@Html.TextAreaFor(m => m.EmpReferences, new { @class = "form-control", @rows = 3 })</div>
                <div class="col-md-5">Character Limit: 255</div>
                @Html.ValidationMessageFor(m => m.EmpReferences)
            </div>
            @*<div class="col-md-12"><td>@Html.LabelFor(m => m.Comments)<td>@Html.TextAreaFor(m => m.Comments, new { @class = "form-control", @rows = 3 })</td><td>Character Limit: 255</td><td>@Html.ValidationMessageFor(m => m.Comments)</td></div>*@

        </div>
    </div>
        <div class="form-group col-md-6">
            <div class="pull-right">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>


        @*<script>


                $('.startdate').datepicker({
                    dateFormat: 'dd/mm/yy',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: '-100:+0',
                    buttonImage: "../../../Content/images/calender-icon.png",
                    showOn: "both",
                    buttonImageOnly: true,
                    //maxDate: new Date()
                    maxDate: -1,
                    buttonImageText: "Calendar"
                    //onSelect: function (selected) {
                    //    var dt = new Date(selected);
                    //    dt.setDate(dt.getDate() + 1);
                    //    $("#enddate").datepicker("option", "minDate", dt);
                    //}
                    });




                $('.enddate').datepicker({
                    dateFormat: 'dd/mm/yy',
                    changeMonth: true,
                    changeYear: true,
                    yearRange: '-100:+0',
                    buttonImage: "../../../Content/images/calender-icon.png",
                    showOn: "both",
                    buttonImageOnly: true,
                    //maxDate: new Date()
                    maxDate: -1,
                    buttonImageText: "Calendar"
                    //onSelect: function (selected) {
                    //    var dt = new Date(selected);
                    //    dt.setDate(dt.getDate() - 1);
                    //    $("#startdate").datepicker("option", "maxDate", dt);
                    //}
                });

            </script>*@



}

HRMS.Web/Views/PastEmployment/PastEmploymentDocs.cshtml
@model HRMS.Entities.PastEmploymentModel



    <table class="display table table-bordered table-striped" width="100%" data-toggle="table" data-cache="false" data-height="299">

    <thead>
        <tr>
            <th>FileName</th>
            <th>Description</th>
            <th>Size</th>
            <th>Type</th>
            <th>Action</th>
        </tr>

    </thead>

    <tbody>
        @foreach (HRMS.Entities.PastEmploymentModel pastEmplotmentmodel in Model.objPastEmploymentList)
        {
            <tr>
                <td>@Html.ActionLink(pastEmplotmentmodel.FileName, "DownloadPastEmploymentDocs", "PastEmployment", new { filename = pastEmplotmentmodel.FileName }, null)  @*@pastEmplotmentmodel.FileName*@ </td>

                <td> @pastEmplotmentmodel.Description </td>
                <td> @pastEmplotmentmodel.FileSize</td>
                <td>@pastEmplotmentmodel.FileType</td>
                <td><a href="#" onclick="RemoveDocs(@pastEmplotmentmodel.AttatchmentId)">Remove</a></td>
            </tr>
        }
    </tbody>
</table>





@Html.HiddenFor(m => m.PastEmploymentID, new { @class = "hiddenEmploymentID" })
<br />



<table>

    <tr>
        <td>@Html.LabelFor(m => m.Description)</td>
        <td>@Html.TextBoxFor(m => m.Description)</td>
        <td>@Html.ValidationMessageFor(m => m.Description)</td>
    </tr>
    <tr>
        <td>@Html.LabelFor(m => m.FileType)</td>
        <td>@Html.TextBoxFor(m => m.FileType)</td>
        <td>@Html.ValidationMessageFor(m => m.FileType)</td>
    </tr>

    <tr>
        <td>
            <label>Upload File:    </label>
        </td>
        <td>
            <input type="file" id="file" name="file" data-val="true" data-val-required="File is required" />
        </td>
        <td></td>
    </tr>


</table>
<input type="submit" value="Save" onclick="SubmitButtonOnclick()">




<script>

    function SubmitButtonOnclick() {
      
        if (validateInput() == true) {
            if($('#PastEmploymentID').val()!='0')
            {
                var formData = new FormData();
                var coverfile = document.getElementById("file").files[0];
                //alert(coverfile);

                formData.append("file", coverfile);
                formData.append("PastEmploymentID", $('#PastEmploymentID').val());
                formData.append("Description", $('#Description').val());
                formData.append("FileType", $('#FileType').val());
                var xhr = new XMLHttpRequest();
                xhr.open("POST", "/PastEmployment/Upload", true);
                xhr.addEventListener("load", function (evt, result) { UploadComplete(evt, result); }, false);
                xhr.addEventListener("error", function (evt) { UploadFailed(evt); }, false);
                xhr.send(formData);
            }
            else
            {
                ShowMessage("warning", "Please fill Pastemployment details first.")
                
            }
        }
        else
        {
            ShowMessage("warning", "Please fill all the details in attatchments.")           
            
        }
    }


    function validateInput()
    {
       
        if($('#Description').val()=="" || $('#FileType').val()=="" || document.getElementById("file").files[0]==null)
        {            
            return false;
        }
        else
        {
            return true;
        }
    }

    function UploadComplete(evt, result) {

        if (evt.target.status == 200) {
            //alert("File uploaded successfully.");
            ShowMessage("success","File uploaded successfully.");
            var data = null;
            var url = window.location + " #grid";
            //$('#grid').load(url, data);

            GetPastEmployment();
        }
        else {
            $.MessageBox({
                buttonDone: "Ok",
                message: evt.target.statusText,
            });
        }
    }

    function UploadFailed(evt) {
        //alert("There was an error attempting to upload the file.");
        ShowMessage("error","File uploaded successfully.");
    }

    function RemoveDocs(id) {
        $.MessageBox({ buttonDone: "Yes", buttonFail: "No", message: "Are you sure you want to delete?" }).done(function () {
            $.ajax({
                dataType: 'json',
                type: 'POST',
                data: { Id: id },
                url: '/PastEmployment/Remove',
                success: function (data) {
                    GetPastEmployment();                    
                    ShowMessage(data.result,data.resultMessage)
                },
                error: function (data) { }
            });
        });
    }

</script>