HRMS.Web/Controllers/ChangePasswordController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using HRMS.DataAccess;
using HRMS.Entities;

namespace HRMS.Web.Controllers
{
    public class ChangePasswordController: Controller
    {
        //
        // GET: /ChangePassword/
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(HRMS.Entities.ChangePassword objChangePassword)
        {
            if (ModelState.IsValid)
            {
                if ((string)Session["defaultPassword"] == objChangePassword.oldPassword)
                {
                    if (objChangePassword.oldPassword == objChangePassword.newPassword)
                    {
                        ViewData["ErrorMessage"] = "Your Old and new password can't be same";
                    }
                    else
                    {
                        EmployeeCredentialModel objEmployeeCredentialModel = new EmployeeCredentialModel();
                        EmployeeCredentialDB objEmployeeCredentialDB = new EmployeeCredentialDB();

                        objEmployeeCredentialModel.EmployeeId = Convert.ToInt16(Session["EmployeeId"].ToString());                        
                        objEmployeeCredentialModel.Password = objChangePassword.newPassword;// new EncryptDecrypt().EncryptPassword(objChangePassword.newPassword);
                        objEmployeeCredentialModel.ModifiedBy = Convert.ToInt16(Session["EmployeeId"].ToString());
                        if (objEmployeeCredentialDB.UpdateEmployeePassword(objEmployeeCredentialModel).StartsWith("Success"))
                        {
                            Session.Remove("defaultPassword");
                            return RedirectToAction("Index", "Employee");
                        }
                        else
                        {
                            ViewData["ErrorMessage"] = "Your password change was unsuccessful.";
                        }
                    }
                }
                else
                {
                    ViewData["ErrorMessage"] = "Your Old password is incorrect";
                }
            }
            return View(objChangePassword);
        }
    }
}

HRMS.Web/Views/ChangePassword/Index.cshtml
@{
    ViewBag.Title = "Account - Change Password";
}
@{
    Layout = null;
}
@model  HRMS.Entities.ChangePassword
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Change Password</title>
</head>
<body>
    <h2>@ViewBag.Title</h2>
    <label style="color:red;">
        @if (ViewData["ErrorMessage"] != null)
        {
            @Html.Label("", ViewData["ErrorMessage"].ToString())
        }
    </label>

    <div class="row">
        <div class="col-md-8">
            <section id="changePassword"> 
                @using (Html.BeginForm("Index", "ChangePassword", new { ReturnUrl = ViewBag.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
                {
                    <h4>Change Password</h4>
                    <hr />
                    @Html.ValidationSummary(true)
                    <div class="form-group">
                        @Html.LabelFor(m => m.oldPassword, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(m => m.oldPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.oldPassword)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.newPassword, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.newPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.newPassword)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(m => m.confirmNewPassword, new { @class = "col-md-2 control-label" })
                        <div class="col-md-10">
                            @Html.PasswordFor(m => m.confirmNewPassword, new { @class = "form-control" })
                            @Html.ValidationMessageFor(m => m.confirmNewPassword)
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Change" class="btn btn-default" />
                        </div>
                    </div>
                }
            </section>
        </div>
    </div>
</body>
</html>