HRMS.Web/Controllers/GeneralControlController.cs
using HRMS.DataAccess;
using HRMS.DataAccess.GeneralDB;
using HRMS.Entities;
using HRMS.Entities.General;
using HRMS.Entities.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Web;
using System.IO;
using System.Web.Mvc;
using System.Drawing.Imaging;
using HRMS.Web.FileUpload;
using Newtonsoft.Json;
using System.Data;
using System.Data.OleDb;
using System.Configuration;
using HRMS.DataAccess.FormsDB;
namespace HRMS.Web.Controllers
{
    public class GeneralControlController : BaseController
    {
        // GET: General
        public ActionResult Index()
        {
            // Session["SelectedGeneral"] = 0;
            List<SelectListItem> ObjSelectedList = new List<SelectListItem>();
            // ObjSelectedList.Add(new SelectListItem { Text = "Select Control", Value = "0" });
            //ObjSelectedList.Add(new SelectListItem { Text = "Pay Banks", Value = "1" });
            //ObjSelectedList.Add(new SelectListItem { Text = "Pay Bank Groups", Value = "12" });
            //*** Naresh 2020-03-19 Hide Employee Section
            //ObjSelectedList.Add(new SelectListItem { Text = "Employee Section", Value = "2" });
            //ObjSelectedList.Add(new SelectListItem { Text = "Employee ID Setting", Value = "3" });
            //ObjSelectedList.Add(new SelectListItem { Text = "Generate Work Email", Value = "4" });
            //ObjSelectedList.Add(new SelectListItem { Text = "Document Setting", Value = "5" });
            // ObjSelectedList.Add(new SelectListItem { Text = "Absent Type", Value = "6" });
            // ObjSelectedList.Add(new SelectListItem { Text = "Validation Setting", Value = "7" });
            ObjSelectedList.Add(new SelectListItem { Text = "MOL Title", Value = "8" });
            ObjSelectedList.Add(new SelectListItem { Text = "SMTP/Email Configuration", Value = "9" });
            //ObjSelectedList.Add(new SelectListItem { Text = "Accrual Leave Balance", Value = "10" });
            ObjSelectedList.Add(new SelectListItem { Text = "Employee Sponsor", Value = "11" });
            ObjSelectedList.Add(new SelectListItem { Text = "Academic Institutes", Value = "13" });
            ObjSelectedList.Add(new SelectListItem { Text = "Qualification Details", Value = "14" });
            ObjSelectedList.Add(new SelectListItem { Text = "Subject Details", Value = "15" });
            ObjSelectedList.Add(new SelectListItem { Text = "Application Logos", Value = "16" });
            // ObjSelectedList.Add(new SelectListItem { Text = "Pay Category List", Value = "17" });
            //ObjSelectedList.Add(new SelectListItem { Text = "Pay Sundry Type", Value = "18" });
            ObjSelectedList.Add(new SelectListItem { Text = "Reminders Setup", Value = "22" });
            ObjSelectedList.Add(new SelectListItem { Text = "Training Competencies", Value = "23" });
            ObjSelectedList.Add(new SelectListItem { Text = "Data Import", Value = "19" });
            // ObjSelectedList.Add(new SelectListItem { Text = "Short Leave Settings", Value = "20" });
            ObjSelectedList.Add(new SelectListItem { Text = "Insurance Category Amount", Value = "21" });
            ViewBag.ControlList = new SelectList(ObjSelectedList, "Value", "Text");
            UserContextViewModel objUserContextViewModel = new UserContextViewModel();
            objUserContextViewModel = (UserContextViewModel)Session["userContext"];
            ViewBag.IsAdmin = objUserContextViewModel.UserId;
            DataImportDB objDataImportDB = new DataImportDB();
            ViewBag.ImportTypeList = new SelectList(objDataImportDB.GetDataImportTypeList(), "ImportTypeID", "ImportTypeName");
            List<PickList> insuranceTypeList = new InsuranceDB().GetInsuranceTypeList();
            string insuranceTypes = "";
            insuranceTypes += "<option value=''>Select Company</option>";
            foreach (var obj in insuranceTypeList)
            {
                insuranceTypes += "<option value='" + obj.id + "'>" + obj.text + "</option>";
            }
            ViewBag.InsuranceType = insuranceTypes;
            List<AcademicYearModel> academicYearList = new AcademicYearDB().GetAllAcademicYear();
            string academicYears = "";
            insuranceTypes += "<option value=''>Select Company</option>";
            foreach (var obj in academicYearList)
            {
                academicYears += "<option value='" + obj.AcademicYearId + "'>" + obj.Year + "</option>";
            }
            ViewBag.AcademicYearList = academicYears;
            return View();
        }

        public ActionResult GetBankList()
        {
            DBHelper objDBHelper = new DBHelper();
            //-------------------Grid Paging Info----------------------------------
            List<PayBanksModel> objBankList = new List<PayBanksModel>();
            BankInformationDB objBankInformationDB = new BankInformationDB();
            UserContextViewModel objUserContextViewModel = new UserContextViewModel();
            objUserContextViewModel = (UserContextViewModel)Session["userContext"];
            objBankList = objBankInformationDB.GetBankListPaging();
            //---------------------------------------------
            var vList = new object();
            vList = new
            {
                aaData = (from item in objBankList
                          select new
                          {
                              Action = "<a class='btn btn-success btn-rounded btn-condensed btn-sm' onclick='AddEditGeneralControl(" + item.BankID.ToString() + ")' title='Edit' ><i class='fa fa-pencil'></i> </a><a class='btn btn-default btn-rounded btn-condensed btn-sm' onclick='ViewGeneralControl(" + item.BankID.ToString() + ")' title='View' ><i class='fa fa-eye'></i> </a><a class='btn btn-danger btn-rounded btn-condensed btn-sm' onclick='DeleteGeneralControl(" + item.BankID.ToString() + ")' title='Edit' ><i class='fa fa-times'></i> </a>",
                              BankName_1 = item.BankName_1,
                              BankName_2 = item.BankName_2,
                              BankName_3 = item.BankName_3,
                              BankGroup = item.BankGroupName,
                              acc_code = item.acc_code,
                              RtnCode = item.RtnCode,
                              SwiftCode = item.SwiftCode,
                              CashBank = item.CashBank ? "<input type='checkbox' class='checkbox' checked='true' disabled id='" + item.BankID + "'/>" : "<input type='checkbox' class='checkbox' disabled id='" + item.BankID + "'/>"
                          }).ToArray()
            };
            return Json(vList, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AddEditBankDetails(int id)
        {
            BankInformationDB objBankInfoDB = new BankInformationDB();
            PayBanksModel objPayBank = new PayBanksModel();
            List<SelectListItem> ObjSelectedList = new List<SelectListItem>();
            // ObjSelectedList.Add(new SelectListItem { Text = "Select Account Code", Value = "0" });
            foreach (var m in new GeneralAccountsDB().GetAccountCode())
            {
                ObjSelectedList.Add(new SelectListItem { Text = m.text.ToString(), Value = m.selectedValue.ToString() });
            }
            ViewBag.lstAccountCode = ObjSelectedList;
            ObjSelectedList = new List<SelectListItem>();
            ObjSelectedList.Add(new SelectListItem { Text = "Select Bank Group", Value = "" });
            foreach (var m in objBankInfoDB.GetBankgroupList().Where(m => m.IsActive == true))
            {
                ObjSelectedList.Add(new SelectListItem { Text = m.BankGroupName_1, Value = m.BankGroupID.ToString() });
            }
            ViewBag.BankGroupList = ObjSelectedList;

            ObjSelectedList = new List<SelectListItem>();
            ObjSelectedList.Add(new SelectListItem { Text = "Select Pay Mode", Value = "" });
            foreach (var m in objBankInfoDB.GetPayBanksModeList().Where(m => m.IsActive == true))
            {
                ObjSelectedList.Add(new SelectListItem { Text = m.PayBanksModeName_1, Value = m.PayBanksModeID.ToString() });
            }
            ViewBag.PayBankModeList = ObjSelectedList;

            if (id != 0)
            {
                objPayBank = objBankInfoDB.GetBankdetailsById(id);
            }
            return View(objPayBank);
        }

        [HttpPost]
        public ActionResult AddEditBankDetails(PayBanksModel PayBank)
        {
            OperationDetails objOperationDetails = new OperationDetails();
            BankInformationDB objBankInfoDB = new BankInformationDB();
            if (PayBank.BankID == 0)
            {
                objOperationDetails = objBankInfoDB.AddEditBank(PayBank, 1);
            }
            else
            {
                objOperationDetails = objBankInfoDB.AddEditBank(PayBank, 2);
            }
            return Json(objOperationDetails, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ViewBankDetails(int id)
        {
            BankInformationDB objBankInfoDB = new BankInformationDB();
            PayBanksModel objPayBank = new PayBanksModel();
            if (id != 0)
            {
                objPayBank = objBankInfoDB.GetBankdetailsById(id);
            }
            return View(objPayBank);
        }

        public ActionResult DeleteBank(int id)
        {
            OperationDetails objOperationDetails = new OperationDetails();
            BankInformationDB objBankInfoDB = new BankInformationDB();
            PayBanksModel objPayBank = new PayBanksModel();
            objPayBank.BankID = id;
            objOperationDetails = objBankInfoDB.AddEditBank(objPayBank, 3);

            return Json(objOperationDetails, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetEmployeeSectionList(int empid = 0)
        {

HRMS.Web/Views/GeneralControl/AddEditAbsentType.cshtml
@model HRMS.Entities.AbsentTypeModel

@{
    Layout = null;
}

<script>

    $("#btnCancel").click(function () {
        $("#myModal").modal("hide");
    });
    $(document).ready(function () {

        var isDeductionChecked = $("#ISDeductable").is(":checked");
        if (isDeductionChecked) {
            $("#DeductionSetting").removeClass("hidden");
        }
        else {
            $("#DeductionSetting").addClass("hidden");
        }
    });

    function onFailure(xhr, status, error) {

        console.log("xhr", xhr);
        console.log("status", status);

        // TODO: make me pretty
        ShowMessage("error", error);
    }

    function onSuccess(data, status, xhr) {

        console.log("data", data);
        console.log("status", status);
        console.log("xhr", xhr);

        if (data.Success == true) {
            ShowMessage("success", data.Message);
            $("#myModal").modal("hide");
            getGridAbsentTypes();
        }
        else {
            ShowMessage("error", data.Message);
        }
    }

    $("#ISDeductable").click(function () {
        showOtherDeductionSetting();
    })

    function showOtherDeductionSetting() {
        var isChecked = $("#ISDeductable").is(":checked");
        if (isChecked) {
            $("#DeductionSetting").removeClass("hidden");
        }
        else {
            $("#DeductionSetting").addClass("hidden");
            $("#DeductAdjacentOffdays").prop('checked', false);
            $("#DeductEnClosedOffdays").prop('checked', false);
            $("#DeductAdjAcentHoliday").prop('checked', false);
        }
    }
</script>
<div class="panel panel-default" id="divAcademic">
    @using (Ajax.BeginForm("AddEditAbsentType", "GeneralControl", new AjaxOptions { OnFailure = "onFailure", OnSuccess = "onSuccess" }, new { id = "frmAddEditAbsentType" }))
    {
        @Html.HiddenFor(x => x.PayAbsentTypeID)
        <div class="panel-body">
            <div class="form-horizontal col-lg-12 col-md-12">
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                    </div>
                    <div class="col-sm-9">
                        <div class="text-right">
                            <span class="required-field">*</span>&nbsp;Indicate required fields
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form"><span class="required-field">*</span>&nbsp;Absent Type Name (EN):</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.PayAbsentTypeName_1, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.PayAbsentTypeName_1)
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form">Absent Type Name (AR):</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.PayAbsentTypeName_2, new { @class = "form-control" })

                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form">Absent Type Name (FR):</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.PayAbsentTypeName_3, new { @class = "form-control" })

                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form">Select Paid Type:</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.DropDownListFor(m => m.PaidType, (SelectList)ViewBag.PaidTypes, new { @class = "form-control selectpickerddl" })
                        @Html.ValidationMessageFor(m => m.PaidType)
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label for="AnnualLeave">Is Annual:</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.CheckBoxFor(m => m.AnnualLeave)
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0 margin_bottom">
                    <div class="col-sm-4 padding-0">
                        <label for="ISDeductable">Is Deductable:</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.CheckBoxFor(m => m.ISDeductable)
                    </div>
                </div>
                <div id="DeductionSetting" class="hidden">
                    <div class="form-group col-md-12 padding-0 margin_bottom">
                        <div class="col-sm-4 padding-0">
                            <label for="DeductAdjacentOffdays">
                                Deduct adjacent offdays:&nbsp;
                            </label>
                            <span data-toggle="tooltip" data-placement="top" title="" data-original-title="If absence occures right before or after offday, then offdays will be deducted." class="information-icon fa fa-info-circle cursorPointer" aria-hidden="true"></span>
                        </div>
                        <div class="col-sm-8">
                            @Html.CheckBoxFor(m => m.DeductAdjacentOffdays)
                        </div>
                    </div>
                    <div class="form-group col-md-12 padding-0 margin_bottom">
                        <div class="col-sm-4 padding-0">
                            <label for="DeductEnClosedOffdays">Deduct enclosed offdays:&nbsp;</label>
                            <span data-toggle="tooltip" data-placement="top" title="" data-original-title="If absence occures before and after offday, then offdays will be deducted." class="information-icon fa fa-info-circle cursorPointer" aria-hidden="true"></span>
                        </div>
                        <div class="col-sm-8">
                            @Html.CheckBoxFor(m => m.DeductEnClosedOffdays)
                        </div>
                    </div>
                    <div class="form-group col-md-12 padding-0 margin_bottom">
                        <div class="col-sm-4 padding-0">
                            <label for="DeductAdjAcentHoliday">Deduct adjacent holiday:&nbsp;</label>
                            <span data-toggle="tooltip" data-placement="top" title="" data-original-title="If absence occures before or after holidays, then holidays will be deducted." class="information-icon fa fa-info-circle cursorPointer" aria-hidden="true"></span>
                        </div>
                        <div class="col-sm-8">
                            @Html.CheckBoxFor(m => m.DeductAdjAcentHoliday)
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" id="btnSubmit" class="btn btn-primary pull-right" value="Save" />
            <input type="button" id="btnCancel" class="btn btn-primary pull-left" value="Cancel" />
        </div>
    }
</div>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/Custom/LaunchDatepicker.js"></script>

HRMS.Web/Views/GeneralControl/AddEditAcademicInstitutes.cshtml
@model HRMS.Entities.General.HRInstituteModel

@{
    Layout = null;
}

<script>

    $("#btnCancel").click(function () {
        $("#myModal").modal("hide");
    });

    function onFailure(xhr, status, error) {

        console.log("xhr", xhr);
        console.log("status", status);

        // TODO: make me pretty
        ShowMessage("error", error);
    }

    function onSuccess(data, status, xhr) {

        console.log("data", data);
        console.log("status", status);
        console.log("xhr", xhr);

        if (data.Success == true) {
            ShowMessage("success", data.Message);
            $("#myModal").modal("hide");
            getAcademicInstitutes();
        }
        else {
            ShowMessage("error", data.Message);
        }
    }
</script>
<div class="panel panel-default" id="divAcademic">
    @using (Ajax.BeginForm("AddEditAcademicInstitutes", "GeneralControl", new AjaxOptions { OnFailure = "onFailure", OnSuccess = "onSuccess" }, new { id = "frmAddEditBankGroup" }))
    {
        @Html.HiddenFor(x => x.HRInstituteID)
        <div class="panel-body">
            <div class="form-horizontal col-lg-12 col-md-12">
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                    </div>
                    <div class="col-sm-9">
                        <div class="text-right">
                            <span class="required-field">*</span>&nbsp;Indicate required fields
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form"><span class="required-field">*</span>&nbsp;Academic Institute (EN):</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.HRInstituteName_1, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.HRInstituteName_1)
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form">Academic Institute (AR):</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.HRInstituteName_2, new { @class = "form-control" })

                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form">Academic Institute (FR):</label>
                    </div>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(m => m.HRInstituteName_3, new { @class = "form-control" })

                    </div>
                </div>             
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-4 padding-0">
                        <label class="label-form" for="IsActive">Is Active:</label>
                    </div>
                    <div class="col-sm-1">
                        <div class="checkbox">
                            <label>@Html.CheckBoxFor(m => m.IsActive)</label>
                        </div>
                    </div>
                </div>
          
               
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" id="btnSubmit" class="btn btn-primary pull-right" value="Save" />
            <input type="button" id="btnCancel" class="btn btn-primary pull-left" value="Cancel" />
        </div>
    }
</div>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

HRMS.Web/Views/GeneralControl/AddEditBankDetails.cshtml
@model HRMS.Entities.General.PayBanksModel

@{
    Layout = null;
}

<script>

    $("#btnCancel").click(function () {
        $("#myModal").modal("hide");
    });

    function onFailure(xhr, status, error) {

        console.log("xhr", xhr);
        console.log("status", status);

        // TODO: make me pretty
        ShowMessage("error", error);
    }

    function onSuccess(data, status, xhr) {

        console.log("data", data);
        console.log("status", status);
        console.log("xhr", xhr);

        if (data.Success == true) {
            ShowMessage("success", data.Message);
            $("#myModal").modal("hide");
            getGridBankDetails();
        }
        else {
            ShowMessage("error", data.Message);
        }
    }
</script>
<div class="panel panel-default" id="divAcademic">
    @using (Ajax.BeginForm("AddEditBankDetails", "GeneralControl", new AjaxOptions { OnFailure = "onFailure", OnSuccess = "onSuccess" }, new { id = "frmAddEditBankdetails" }))
    {
        @Html.HiddenFor(x => x.BankID)
        <div class="panel-body">
            <div class="form-horizontal col-lg-12 col-md-12">
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                    </div>
                    <div class="col-sm-9">
                        <div class="text-right">
                            <span class="required-field">*</span>&nbsp;Indicate required fields
                        </div>
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form"><span class="required-field">*</span>&nbsp;Name of Bank (EN):</label>
                    </div>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.BankName_1, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.BankName_1)
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form">Name of Bank (AR):</label>
                    </div>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.BankName_2, new { @class = "form-control" })

                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form">Name of Bank (FR):</label>
                    </div>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.BankName_3, new { @class = "form-control" })

                    </div>
                </div>
                @*<div class="form-group col-md-12 padding-0">
                        <div class="col-sm-3 padding-0">
                            <label class="label-form">Tr Date:</label>
                        </div>
                        <div class="col-sm-9">
                            @Html.TextBoxFor(m => m.tr_Date, new { @class = "form-control datepicker" })

                        </div>
                    </div>*@
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form">Bank Group:</label>
                    </div>
                    <div class="col-sm-9">
                        @*@Html.TextBoxFor(m => m.acc_code, new { @class = "form-control" })*@
                        @Html.DropDownListFor(m => m.BankGroupID, (List<SelectListItem>)ViewBag.BankGroupList,new { @class = "form-control selectpickerddl", @data_live_search = "true" })
                        
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form"><span class="required-field">*</span>&nbsp;Salary Payable Account Code:</label>
                    </div>
                    <div class="col-sm-9">
                        @*@Html.TextBoxFor(m => m.acc_code, new { @class = "form-control" })*@
                        @Html.DropDownListFor(m => m.acc_code, (List<SelectListItem>)ViewBag.lstAccountCode, "Select account code", new { @class = "form-control selectpickerddl", @data_live_search = "true" })
                        @Html.ValidationMessageFor(m => m.acc_code)
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form">Pay Mode:</label>
                    </div>
                    <div class="col-sm-9">
                        @Html.DropDownListFor(m => m.PayBanksModeID, (List<SelectListItem>)ViewBag.PayBankModeList, new { @class = "form-control selectpickerddl", @data_live_search = "true" })
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form"><span class="required-field">*</span>&nbsp;Rtn/Routing Code:</label>
                    </div>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.RtnCode, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.RtnCode)
                    </div>
                </div>               
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form"><span class="required-field">*</span>&nbsp;SwiftCode:</label>
                    </div>
                    <div class="col-sm-9">
                        @Html.TextBoxFor(m => m.SwiftCode, new { @class = "form-control", required = "required" })
                        @Html.ValidationMessageFor(m => m.SwiftCode)
                    </div>
                </div>
                <div class="form-group col-md-12 padding-0">
                    <div class="col-sm-3 padding-0">
                        <label class="label-form" for="CashBank">Cash Bank:</label>
                    </div>
                    <div class="col-sm-9">
                        <div class="checkbox">
                            <label>@Html.CheckBoxFor(m => m.CashBank)</label>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="panel-footer">
            <input type="submit" id="btnSubmit" class="btn btn-primary pull-right" value="Save" />
            <input type="button" id="btnCancel" class="btn btn-primary pull-left" value="Cancel" />
        </div>
    }
</div>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/Custom/LaunchDatepicker.js"></script>

HRMS.Web/Views/GeneralControl/ViewAcademicInstitutesDetails.cshtml
@model HRMS.Entities.General.HRInstituteModel

@{
    Layout = null;
}

<script src="~/Scripts/jquery.validate.min.js"></script>
<script>

    $("#btnCancel").click(function () {
        $("#myModal").modal("hide");
    });

</script>


<div class="panel panel-default" id="divAcademic">
    <div class="panel-body">
        <div class="col-md-12">

            <div class="form-group col-md-12 padding-0">
                <label class="col-md-5 control-label">Academic Institute (EN): </label>
                <div class="col-md-7">@Html.DisplayFor(m => m.HRInstituteName_1, new { @class = "form-control" })</div>
            </div>

            <div class="form-group col-md-12 padding-0">
                <label class="col-md-5 control-label">Academic Institute (AR): </label>
                <div class="col-md-7">@Html.DisplayFor(m => m.HRInstituteName_2, new { @class = "form-control" })</div>
            </div>
            <div class="form-group col-md-12 padding-0">
                <label class="col-md-5 control-label">Academic Institute (FR):</label>
                <div class="col-md-7">@Html.DisplayFor(m => m.HRInstituteName_3, new { @class = "form-control" })</div>
            </div>                               
            <div class="form-group col-md-12 padding-0">
                <label class="col-md-5 control-label">Is Active:</label>             
                <div class="col-sm-7" style="padding-top:2px;">                   
                        @Html.CheckBoxFor(m => m.IsActive, new { @Disabled = "Disabled" })                  
                </div>
            </div>
        </div>
    </div>
    <div class="panel-footer">
        <input type="button" id="btnCancel" class="btn btn-primary pull-right" value="Close" />
    </div>
</div>